name: Update README

on: 
  schedule: 
  - cron: '30  6 * * *'

permissions: 
  contents: write

jobs: 
  update-README: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run Python Script
        env: 
          MONKEYTYPE_API_KEY: ${{ secrets.MONKEYTYPE_API_KEY }}
        run: python get-stats.py

      - name: Push Changes
        run: |
          git config --global user.name 'Nate Dixon'
          git config --global user.email 'njdixon23@gmail.com'
          git add .
          git commit -am "MonkeyType Stats Daily Update"
          git push
